<?php
namespace console\controllers;

use common\models\AuthItem;
use yii\console\Controller;

class PermissionController extends Controller
{

    protected $mapping = [
        '@backend.ActorDirector.Create'                  => 'Đạo diễn/Diễn viên; Nhạc sĩ/Ca sĩ: Thêm mới',
        '@backend.ActorDirector.Delete'                  => 'Đạo diễn/Diễn viên; Nhạc sĩ/Ca sĩ: Xóa',
        '@backend.ActorDirector.Index'                   => 'Đạo diễn/Diễn viên; Nhạc sĩ/Ca sĩ: Xem danh sách',
        '@backend.ActorDirector.Update'                  => 'Đạo diễn/Diễn viên; Nhạc sĩ/Ca sĩ: Cập nhật',
        '@backend.ActorDirector.View'                    => 'Đạo diễn/Diễn viên; Nhạc sĩ/Ca sĩ: Xem chi tiết',

        '@backend.Category.Create'                       => 'Danh mục: Thêm mới',
        '@backend.Category.Delete'                       => 'Danh mục: Xóa',
        '@backend.Category.Index'                        => 'Danh mục: Xem danh sách',
        '@backend.Category.MoveDown'                     => 'Danh mục: Di chuyển lên',
        '@backend.Category.MoveUp'                       => 'Danh mục: Di chuyển xuống',
        '@backend.Category.ResetOrder'                   => 'Danh mục: Reset thứ tự',
        '@backend.Category.Update'                       => 'Danh mục: Cập nhật',
        '@backend.Category.View'                         => 'Danh mục: Xem chi tiết',

        '@backend.Content.ChangeContentSiteStatus'       => 'Nội dung: Đổi trạng thái trên nhà cung cấp',
        '@backend.Content.ChangeLiveprogramStatus'       => 'Nội dung: Đổi trạng thái catchup',
        '@backend.Content.Create'                        => 'Nội dung: Thêm mới',
        '@backend.Content.CreateEpg'                     => 'Nội dung: Tạo lịch phát sóng',
        '@backend.Content.Delete'                        => 'Nội dung: Xóa',
        '@backend.Content.DeleteImage'                   => 'Nội dung: Xóa ảnh (trong form tạo mới + cập nhật)',
        '@backend.Content.ExportDataToFile'              => 'Nội dung: Xuất file cho Karaoke',
        '@backend.Content.FindActors'                    => 'Nội dung: Tìm diễn viên (phim), ca sĩ (karaoke)',
        '@backend.Content.FindDirectors'                 => 'Nội dung: Tìm đạo diễn (phim), nhạc sĩ (karaoke)',
        '@backend.Content.Index'                         => 'Nội dung: Xem danh sách',
        '@backend.Content.ModalStreamingServer'          => 'Nội dung: Hiện popup chọn địa chỉ phân phối nội dung',
        '@backend.Content.RelatedList'                   => 'Nội dung: Tìm kiếm nội dung liên quan',
        '@backend.Content.ReleaseStaticData'             => 'Nội dung: Xuất file cho Karaoke',
        '@backend.Content.SyncContentToSite'             => 'Nội dung: Phân phối nội dung',
        '@backend.Content.Update'                        => 'Nội dung: Cập nhật',
        '@backend.Content.UpdateStatus'                  => 'Nội dung: Cập nhật trạng thái (cập nhật nhanh trạng thái trang index)',
        '@backend.Content.UpdateStatusContent'           => 'Nội dung: Cập nhật trạng thái (các nút trạng thái trên đầu danh sách nội dung)',
        '@backend.Content.UpdateVersionApi'              => 'Nội dung: Cập nhật phiên bản API',
        '@backend.Content.UploadFile'                    => 'Nội dung: Upload ảnh',
        '@backend.Content.View'                          => 'Nội dung: Xem chi tiết',

        '@backend.ContentAttribute.Create'               => 'Thuộc tính động cho nội dung: Thêm mới',
        '@backend.ContentAttribute.Delete'               => 'Thuộc tính động cho nội dung: Xóa',
        '@backend.ContentAttribute.Index'                => 'Thuộc tính động cho nội dung: Xem danh sách',
        '@backend.ContentAttribute.Update'               => 'Thuộc tính động cho nội dung: Cập nhật',
        '@backend.ContentAttribute.View'                 => 'Thuộc tính động cho nội dung: Xem chi tiết',

        '@backend.ContentFeedback.Approve'               => 'Nhận xét về Nội dung: Duyệt nhận xét',
        '@backend.ContentFeedback.Create'                => 'Nhận xét về Nội dung: Thêm mới',
        '@backend.ContentFeedback.Delete'                => 'Nhận xét về Nội dung: Xóa',
        '@backend.ContentFeedback.Index'                 => 'Nhận xét về Nội dung: Xem danh sách',
        '@backend.ContentFeedback.Reject'                => 'Nhận xét về Nội dung: Từ chối nhận xét',
        '@backend.ContentFeedback.Update'                => 'Nhận xét về Nội dung: Cập nhật',
        '@backend.ContentFeedback.View'                  => 'Nhận xét về Nội dung: Xem chi tiết',

        '@backend.ContentLog.Create'                     => 'Log nội dung: Thêm mới',
        '@backend.ContentLog.Delete'                     => 'Log nội dung: Xóa',
        '@backend.ContentLog.Index'                      => 'Log nội dung: Xem danh sách',
        '@backend.ContentLog.Update'                     => 'Log nội dung: Cập nhật',
        '@backend.ContentLog.View'                       => 'Log nội dung: Xem chi tiết',

        '@backend.ContentProfile.Create'                 => 'File nội dung: Thêm mới',
        '@backend.ContentProfile.Delete'                 => 'File nội dung: Xóa',
        '@backend.ContentProfile.Editable'               => 'File nội dung: Sửa nhanh thông tin',
        '@backend.ContentProfile.Index'                  => 'File nội dung: Xem danh sách',
        '@backend.ContentProfile.Update'                 => 'File nội dung: Cập nhật',
        '@backend.ContentProfile.UpdateModalData'        => 'File nội dung: Bật popup cập nhật file nội dung',
        '@backend.ContentProfile.UploadInfo'             => 'File nội dung: Thông tin upload',
        '@backend.ContentProfile.UploadVideo'            => 'File nội dung: Upload file nội dung',
        '@backend.ContentProfile.View'                   => 'File nội dung: Xem chi tiết',
        '@backend.ContentProfile.ViewModalData'          => 'File nội dung: Bật popup xem chi tiết file nội dung',
// '@backend.ItemKodi.Create'          =>               '',
        // '@backend.ItemKodi.Delete'          =>               '',
        // '@backend.ItemKodi.Index'          =>                '',
        // '@backend.ItemKodi.Update'          =>               '',
        // '@backend.ItemKodi.View'          =>                 '',
        // '@backend.KodiAddon.Create'          =>              '',
        // '@backend.KodiAddon.Delete'          =>              '',
        // '@backend.KodiAddon.Index'          =>               '',
        // '@backend.KodiAddon.Update'          =>              '',
        // '@backend.KodiAddon.View'          =>                '',
        // '@backend.KodiCategory.Create'          =>               '',
        // '@backend.KodiCategory.Delete'          =>               '',
        // '@backend.KodiCategory.Index'          =>                '',
        // '@backend.KodiCategory.Update'          =>               '',
        // '@backend.KodiCategory.View'          =>                 '',
        // '@backend.Pricing.View'                          => '',
        '@backend.RbacBackend.CreatePermission'          => 'Quyền Admin: Tạo quyền',
        '@backend.RbacBackend.CreateRole'                => 'Quyền Admin: Tạo nhóm quyền',
        '@backend.RbacBackend.DeletePermission'          => 'Quyền Admin: Xóa quyền',
        '@backend.RbacBackend.DeleteRole'                => 'Quyền Admin: Xóa nhóm quyền',
        '@backend.RbacBackend.GeneratePermission'        => 'Quyền Admin: Khởi tạo quyền',
        '@backend.RbacBackend.GeneratePermissionConfirm' => 'Quyền Admin: Xác nhận khởi tạo quyền',
        '@backend.RbacBackend.GenerateRole'              => 'Quyền Admin: Khởi tạo nhóm quyền',
        '@backend.RbacBackend.GenerateRoleConfirm'       => 'Quyền Admin: Xác nhận khởi tạo nhóm quyền',
        '@backend.RbacBackend.Index'                     => 'Quyền Admin: Xem danh sách',
        '@backend.RbacBackend.Permission'                => 'Quyền Admin: Xem danh sách quyền',
        '@backend.RbacBackend.Role'                      => 'Quyền Admin: Xem danh sách nhóm quyền',
        '@backend.RbacBackend.RoleAddAuthItem'           => 'Quyền Admin: Thêm quyền vào nhóm quyền',
        '@backend.RbacBackend.RoleRevokeAuthItem'        => 'Quyền Admin: Gỡ quyền khỏi nhóm quyền',
        '@backend.RbacBackend.UpdatePermission'          => 'Quyền Admin: Cập nhật quyền',
        '@backend.RbacBackend.UpdateRole'                => 'Quyền Admin: Cập nhật nhóm quyền',
        '@backend.RbacBackend.ViewPermission'            => 'Quyền Admin: Xem quyền',
        '@backend.RbacBackend.ViewRole'                  => 'Quyền Admin: Xem nhóm quyền',

        '@backend.RbacCp.CreatePermission'               => 'Quyền Đại lý: Tạo quyền',
        '@backend.RbacCp.CreateRole'                     => 'Quyền Đại lý: Tạo nhóm quyền',
        '@backend.RbacCp.DeletePermission'               => 'Quyền Đại lý: Xóa quyền',
        '@backend.RbacCp.DeleteRole'                     => 'Quyền Đại lý: Xóa nhóm quyền',
        '@backend.RbacCp.GeneratePermission'             => 'Quyền Đại lý: Khởi tạo quyền',
        '@backend.RbacCp.GeneratePermissionConfirm'      => 'Quyền Đại lý: Xác nhận khởi tạo quyền',
        '@backend.RbacCp.GenerateRole'                   => 'Quyền Đại lý: Khởi tạo nhóm quyền',
        '@backend.RbacCp.GenerateRoleConfirm'            => 'Quyền Đại lý: Xác nhận khởi tạo nhóm quyền',
        '@backend.RbacCp.Index'                          => 'Quyền Đại lý: Xem danh sách',
        '@backend.RbacCp.Permission'                     => 'Quyền Đại lý: Xem danh sách quyền',
        '@backend.RbacCp.Role'                           => 'Quyền Đại lý: Xem danh sách nhóm quyền',
        '@backend.RbacCp.RoleAddAuthItem'                => 'Quyền Đại lý: Thêm quyền vào nhóm quyền',
        '@backend.RbacCp.RoleRevokeAuthItem'             => 'Quyền Đại lý: Gỡ quyền khỏi nhóm quyền',
        '@backend.RbacCp.UpdatePermission'               => 'Quyền Đại lý: Cập nhật quyền',
        '@backend.RbacCp.UpdateRole'                     => 'Quyền Đại lý: Cập nhật nhóm quyền',
        '@backend.RbacCp.ViewPermission'                 => 'Quyền Đại lý: Xem quyền',
        '@backend.RbacCp.ViewRole'                       => 'Quyền Đại lý: Xem nhóm quyền',

        '@backend.RbacSp.CreatePermission'               => 'Quyền Nhà cung cấp: Tạo quyền',
        '@backend.RbacSp.CreateRole'                     => 'Quyền Nhà cung cấp: Tạo nhóm quyền',
        '@backend.RbacSp.DeletePermission'               => 'Quyền Nhà cung cấp: Xóa quyền',
        '@backend.RbacSp.DeleteRole'                     => 'Quyền Nhà cung cấp: Xóa nhóm quyền',
        '@backend.RbacSp.GeneratePermission'             => 'Quyền Nhà cung cấp: Khởi tạo quyền',
        '@backend.RbacSp.GeneratePermissionConfirm'      => 'Quyền Nhà cung cấp: Xác nhận khởi tạo quyền',
        '@backend.RbacSp.GenerateRole'                   => 'Quyền Nhà cung cấp: Khởi tạo nhóm quyền',
        '@backend.RbacSp.GenerateRoleConfirm'            => 'Quyền Nhà cung cấp: Xác nhận khởi tạo nhóm quyền',
        '@backend.RbacSp.Index'                          => 'Quyền Nhà cung cấp: Xem danh sách',
        '@backend.RbacSp.Permission'                     => 'Quyền Nhà cung cấp: Xem danh sách quyền',
        '@backend.RbacSp.Role'                           => 'Quyền Nhà cung cấp: Xem danh sách nhóm quyền',
        '@backend.RbacSp.RoleAddAuthItem'                => 'Quyền Nhà cung cấp: Thêm quyền vào nhóm quyền',
        '@backend.RbacSp.RoleRevokeAuthItem'             => 'Quyền Nhà cung cấp: Gỡ quyền khỏi nhóm quyền',
        '@backend.RbacSp.UpdatePermission'               => 'Quyền Nhà cung cấp: Cập nhật quyền',
        '@backend.RbacSp.UpdateRole'                     => 'Quyền Nhà cung cấp: Cập nhật nhóm quyền',
        '@backend.RbacSp.ViewPermission'                 => 'Quyền Nhà cung cấp: Xem quyền',
        '@backend.RbacSp.ViewRole'                       => 'Quyền Nhà cung cấp: Xem nhóm quyền',

        '@backend.Report.Content'                        => 'Báo cáo: Báo cáo nội dung',
        '@backend.Report.FindCategoryBySiteContent'      => 'Báo cáo: Tìm danh mục theo NCC và nội dung',
        '@backend.Report.FindServiceBySite'              => 'Báo cáo: Tìm gói cước theo NCC',
        '@backend.Report.Revenues'                       => 'Báo cáo: Báo cáo doanh thu',
        '@backend.Report.SubscriberActivity'             => 'Báo cáo: Báo cáo lượt truy cập',
        '@backend.Report.SubscriberDaily'                => 'Báo cáo: Báo cáo số lượng thuê bao',

        '@backend.Service.Approve'                       => 'Gói cước: Duyệt gói cước',
        '@backend.Service.Delete'                        => 'Gói cước: Xóa',
        '@backend.Service.Index'                         => 'Gói cước: Xem danh sách',
        '@backend.Service.Suspend'                       => 'Gói cước: Dừng gói cước',
        '@backend.Service.UpdateNote'                    => 'Gói cước: Cập nhật ghi chú',
        '@backend.Service.View'                          => 'Gói cước: Xem chi tiết',

        '@backend.ServiceGroup.Create'                   => 'Nhóm gói cước: Thêm mới',
        '@backend.ServiceGroup.Delete'                   => 'Nhóm gói cước: Xóa',
        '@backend.ServiceGroup.Index'                    => 'Nhóm gói cước: Xem danh sách',
        '@backend.ServiceGroup.Update'                   => 'Nhóm gói cước: Cập nhật',
        '@backend.ServiceGroup.View'                     => 'Nhóm gói cước: Xem chi tiết',

        '@backend.ServiceProvider.ChangePassword'        => 'Nhà cung cấp: Đổi password',
        '@backend.ServiceProvider.Create'                => 'Nhà cung cấp: Thêm mới',
        '@backend.ServiceProvider.Delete'                => 'Nhà cung cấp: Xóa',
        '@backend.ServiceProvider.DeleteUser'            => 'Nhà cung cấp: Xóa người dùng',
        '@backend.ServiceProvider.Index'                 => 'Nhà cung cấp: Xem danh sách',
        '@backend.ServiceProvider.LoginAsSp'             => 'Nhà cung cấp: Login với tư cách NCC',
        '@backend.ServiceProvider.SyncDataToSite'        => 'Nhà cung cấp: Phân phối nội dung',
        // '@backend.ServiceProvider.Transfer'              => 'Nhà cung cấp: Transfer',
        '@backend.ServiceProvider.Update'                => 'Nhà cung cấp: Cập nhật',
        '@backend.ServiceProvider.UpdateStatus'          => 'Nhà cung cấp: Cập nhật trạng thái (cập nhật nhanh trạng thái trang index)',
        '@backend.ServiceProvider.UpdateUser'            => 'Nhà cung cấp: Cập nhật người quản trị',
        '@backend.ServiceProvider.View'                  => 'Nhà cung cấp: Xem chi tiết',
        '@backend.ServiceProvider.ViewUser'              => 'Nhà cung cấp: Xem chi tiết người quản trị',

        // '@backend.Site.Index'                            => '',
        // '@backend.Site.Login'                            => '',
        // '@backend.Site.Logout'                           => '',

        '@backend.StreamingServer.Create'                => 'Địa chỉ phân phối nội dung: Thêm mới',
        '@backend.StreamingServer.Delete'                => 'Địa chỉ phân phối nội dung: Xóa',
        '@backend.StreamingServer.Index'                 => 'Địa chỉ phân phối nội dung: Xem danh sách',
        '@backend.StreamingServer.Update'                => 'Địa chỉ phân phối nội dung: Cập nhật',
        '@backend.StreamingServer.View'                  => 'Địa chỉ phân phối nội dung: Xem chi tiết',

        '@backend.Subscriber.Create'                     => 'Thuê bao: Thêm mới',
        '@backend.Subscriber.Delete'                     => 'Thuê bao: Xóa',
        '@backend.Subscriber.Index'                      => 'Thuê bao: Xem danh sách',
        '@backend.Subscriber.Update'                     => 'Thuê bao: Cập nhật',
        '@backend.Subscriber.View'                       => 'Thuê bao: Xem chi tiết',

        // '@backend.SumServiceAmount.Create'               => 'Tổng số dịch vụ: Thêm mới',
        // '@backend.SumServiceAmount.Delete'               => 'Tổng số dịch vụ: Xóa',
        // '@backend.SumServiceAmount.Index'                => 'Tổng số dịch vụ: Xem danh sách',
        // '@backend.SumServiceAmount.Update'               => 'Tổng số dịch vụ: Cập nhật',
        // '@backend.SumServiceAmount.View'                 => 'Tổng số dịch vụ: Xem chi tiết',

        '@backend.Transcode.AddFileTranscoded'           => 'File nội dung: Gắn file nội dung',
        '@backend.Transcode.Search'                      => 'File nội dung: Tìm kiếm file nội dung',

        '@backend.User.AddAuthItem'                      => 'Người dùng: Phân quyền',
        '@backend.User.ChangePassword'                   => 'Người dùng: Đổi mật khẩu',
        '@backend.User.Create'                           => 'Người dùng: Thêm mới',
        '@backend.User.Delete'                           => 'Người dùng: Xóa',
        '@backend.User.Index'                            => 'Người dùng: Xem danh sách',
        '@backend.User.Info'                             => 'Người dùng: Xem thông tin người quản trị',
        '@backend.User.OwnerChangePassword'              => 'Người dùng: Đổi mật khẩu người dùng hiện tại',
        '@backend.User.ResetPassword'                    => 'Người dùng: Khôi phục mật khẩu',
        '@backend.User.RevokeAuthItem'                   => 'Người dùng: Xóa quyền',
        '@backend.User.Update'                           => 'Người dùng: Cập nhật',
        '@backend.User.UpdateOwner'                      => 'Người dùng: Cập nhật người dùng hiện tại',
        '@backend.User.View'                             => 'Người dùng: Xem chi tiết',

        '@backend.UserActivity.Index'                    => 'Hành động của người dùng: Xem danh sách',

        /**
         * sp permission ********************************************************************************
         */

        // '@site.View.View'                                => 'View : View',
        // '@site.View.Update'                              => 'View : Update',
        // '@site.View.ResendMt'                            => 'View : ResendMt',
        // '@site.View.PurchaseServicePackage'              => 'View : PurchaseServicePackage',
        // '@site.View.Index'                               => 'View : Index',
        // '@site.View.Delete'                              => 'View : Delete',
        // '@site.View.Create'                              => 'View : Create',
        // '@site.View.CancelServicePackage'                => 'View : CancelServicePackage',

        // '@site.UserActivity.Index'                       => 'UserActivity : Index',

        '@site.User.AddAuthItem'                         => 'Người dùng: Phân quyền',
        '@site.User.ChangePassword'                      => 'Người dùng: Đổi mật khẩu',
        '@site.User.Create'                              => 'Người dùng: Thêm mới',
        '@site.User.Delete'                              => 'Người dùng: Xóa',
        '@site.User.Index'                               => 'Người dùng: Xem danh sách',
        '@site.User.Info'                                => 'Người dùng: Xem thông tin người quản trị',
        '@site.User.OwnerChangePassword'                 => 'Người dùng: Đổi mật khẩu người dùng hiện tại',
        '@site.User.ResetPassword'                       => 'Người dùng: Khôi phục mật khẩu',
        '@site.User.RevokeAuthItem'                      => 'Người dùng: Xóa quyền',
        '@site.User.Update'                              => 'Người dùng: Cập nhật',
        '@site.User.UpdateOwner'                         => 'Người dùng: Cập nhật người dùng hiện tại',
        '@site.User.View'                                => 'Người dùng: Xem chi tiết',

        // '@site.SumViewPartner.View'                      => 'SumViewPartner : View',
        // '@site.SumViewPartner.Update'                    => 'SumViewPartner : Update',
        // '@site.SumViewPartner.Index'                     => 'SumViewPartner : Index',
        // '@site.SumViewPartner.Delete'                    => 'SumViewPartner : Delete',
        // '@site.SumViewPartner.Create'                    => 'SumViewPartner : Create',

        // '@site.SumServiceAmount.View'                    => 'SumServiceAmount : View',
        // '@site.SumServiceAmount.Update'                  => 'SumServiceAmount : Update',
        // '@site.SumServiceAmount.Index'                   => 'SumServiceAmount : Index',
        // '@site.SumServiceAmount.Delete'                  => 'SumServiceAmount : Delete',
        // '@site.SumServiceAmount.Create'                  => 'SumServiceAmount : Create',

        // '@site.SumService.View'                          => 'SumService : View',
        // '@site.SumService.Update'                        => 'SumService : Update',
        // '@site.SumService.Index'                         => 'SumService : Index',
        // '@site.SumService.Delete'                        => 'SumService : Delete',
        // '@site.SumService.Create'                        => 'SumService : Create',

        // '@site.SumContentView.View'                      => 'SumContentView : View',
        // '@site.SumContentView.Update'                    => 'SumContentView : Update',
        // '@site.SumContentView.Index'                     => 'SumContentView : Index',
        // '@site.SumContentView.Delete'                    => 'SumContentView : Delete',
        // '@site.SumContentView.Create'                    => 'SumContentView : Create',

        // '@site.SumContentUpload.View'                    => 'SumContentUpload : View',
        // '@site.SumContentUpload.Update'                  => 'SumContentUpload : Update',
        // '@site.SumContentUpload.Index'                   => 'SumContentUpload : Index',
        // '@site.SumContentUpload.Delete'                  => 'SumContentUpload : Delete',
        // '@site.SumContentUpload.Create'                  => 'SumContentUpload : Create',

        // '@site.SumContentDownload.View'                  => 'SumContentDownload : View',
        // '@site.SumContentDownload.Update'                => 'SumContentDownload : Update',
        // '@site.SumContentDownload.Index'                 => 'SumContentDownload : Index',
        // '@site.SumContentDownload.Delete'                => 'SumContentDownload : Delete',
        // '@site.SumContentDownload.Create'                => 'SumContentDownload : Create',

        // '@site.SumContent.View'                          => 'SumContent : View',
        // '@site.SumContent.Update'                        => 'SumContent : Update',
        // '@site.SumContent.Index'                         => 'SumContent : Index',
        // '@site.SumContent.Delete'                        => 'SumContent : Delete',
        // '@site.SumContent.Create'                        => 'SumContent : Create',

//        '@site.SubscriberDeviceAsm.View'                 => 'SubscriberDeviceAsm : View',
//        '@site.SubscriberDeviceAsm.Update'               => 'SubscriberDeviceAsm : Update',
//        '@site.SubscriberDeviceAsm.Index'                => 'SubscriberDeviceAsm : Index',
//        '@site.SubscriberDeviceAsm.Delete'               => 'SubscriberDeviceAsm : Delete',
//        '@site.SubscriberDeviceAsm.Create'               => 'SubscriberDeviceAsm : Create',

//        '@site.SubscriberActivity.View'                  => 'SubscriberActivity : View',
//        '@site.SubscriberActivity.Update'                => 'SubscriberActivity : Update',
//        '@site.SubscriberActivity.Index'                 => 'SubscriberActivity : Index',
//        '@site.SubscriberActivity.Delete'                => 'SubscriberActivity : Delete',
//        '@site.SubscriberActivity.Create'                => 'SubscriberActivity : Create',

        '@site.Subscriber.View'                          => 'Thuê bao : Xem',
        '@site.Subscriber.Update'                        => 'Thuê bao : Cập nhật',
        '@site.Subscriber.UnassignDeviceForSubscriber'   => 'Thuê bao : Bỏ gán thiết bị',
//        '@site.Subscriber.ResendMt'                      => 'Thuê bao : ResendMt',
        '@site.Subscriber.PurchaseServicePackages'       => 'Thuê bao : Mua gói cước',
        '@site.Subscriber.Index'                         => 'Thuê bao : Danh sách',
        '@site.Subscriber.ExtendServicePackage'          => 'Thuê bao : Gia hạn gói cước',
        '@site.Subscriber.Delete'                        => 'Thuê bao : Xóa',
        '@site.Subscriber.Create'                        => 'Thuê bao : Tạo',
        '@site.Subscriber.CancelServicePackage'          => 'Thuê bao : Hủy gói',
        '@site.Subscriber.AssignDevicesForSubscriber'    => 'Thuê bao : Gán thiết bị cho thuê bao',

        // '@site.Site.Logout'                              => 'Site : Logout',
        // '@site.Site.LoginAs'                             => 'Site : LoginAs',
        // '@site.Site.Login'                               => 'Site : Login',
        // '@site.Site.Index'                               => 'Site : Index',

        '@site.ServiceGroup.View'                        => 'Nhóm gói cước : Xem',
        '@site.ServiceGroup.Update'                      => 'Nhóm gói cước : Sửa',
        '@site.ServiceGroup.Index'                       => 'Nhóm gói cước : Xem danh sách',
        '@site.ServiceGroup.Delete'                      => 'Nhóm gói cước : Xóa',
        '@site.ServiceGroup.Create'                      => 'Nhóm gói cước : Tạo',

        '@site.Service.View'                             => 'Gói cước : Xem chi tiết',
        '@site.Service.UpdateStatus'                     => 'Gói cước : Cập nhật trạng thái',
        '@site.Service.UpdateServiceCategoryAsm'         => 'Gói cước : Cập nhật danh mục gói cước',
        '@site.Service.Update'                           => 'Gói cước : Cập nhật thông tin gói cước',
        // '@site.Service.UnsetDefault'                     => 'Gói cước : UnsetDefault',
        // '@site.Service.SetDefault'                       => 'Gói cước : SetDefault',
        '@site.Service.Index'                            => 'Gói cước : Xem danh sách',
        '@site.Service.Delete'                           => 'Gói cước : Xóa',
        // '@site.Service.CreateTemp'                       => 'Gói cước : CreateTemp',
        '@site.Service.Create'                           => 'Gói cước : Tạo',
        '@site.Service.Approve'                          => 'Gói cước : Duyệt',

        '@site.Report.Content'                           => 'Báo cáo: Báo cáo nội dung',
        '@site.Report.FindCategoryBySiteContent'         => 'Báo cáo: Tìm danh mục theo NCC và nội dung',
        '@site.Report.FindServiceBySite'                 => 'Báo cáo: Tìm gói cước theo NCC',
        '@site.Report.Revenues'                          => 'Báo cáo: Báo cáo doanh thu',
        '@site.Report.SubscriberActivity'                => 'Báo cáo: Báo cáo lượt truy cập',
        '@site.Report.SubscriberDaily'                   => 'Báo cáo: Báo cáo số lượng thuê bao',

        // '@site.Rbac.ViewRole'                            => 'Rbac : ViewRole',
        // '@site.Rbac.ViewPermission'                      => 'Rbac : ViewPermission',
        // '@site.Rbac.UpdateRole'                          => 'Rbac : UpdateRole',
        // '@site.Rbac.UpdatePermission'                    => 'Rbac : UpdatePermission',
        // '@site.Rbac.RoleRevokeAuthItem'                  => 'Rbac : RoleRevokeAuthItem',
        // '@site.Rbac.RoleAddAuthItem'                     => 'Rbac : RoleAddAuthItem',
        // '@site.Rbac.Role'                                => 'Rbac : Role',
        // '@site.Rbac.Permission'                          => 'Rbac : Permission',
        // '@site.Rbac.Index'                               => 'Rbac : Index',
        // '@site.Rbac.GenerateRoleConfirm'                 => 'Rbac : GenerateRoleConfirm',
        // '@site.Rbac.GenerateRole'                        => 'Rbac : GenerateRole',
        // '@site.Rbac.GeneratePermissionConfirm'           => 'Rbac : GeneratePermissionConfirm',
        // '@site.Rbac.GeneratePermission'                  => 'Rbac : GeneratePermission',
        // '@site.Rbac.DeleteRole'                          => 'Rbac : DeleteRole',
        // '@site.Rbac.DeletePermission'                    => 'Rbac : DeletePermission',
        // '@site.Rbac.CreateRole'                          => 'Rbac : CreateRole',
        // '@site.Rbac.CreatePermission'                    => 'Rbac : CreatePermission',

        '@site.Pricing.View'                             => 'Giá : Xem',
        '@site.Pricing.Update'                           => 'Giá : Sửa',
        '@site.Pricing.Index'                            => 'Giá : Xem danh sách',
        '@site.Pricing.Delete'                           => 'Giá : Xóa',
        '@site.Pricing.Create'                           => 'Giá : Tạo',

        '@site.Device.View'                              => 'Thiết bị : Xem',
        '@site.Device.UpdateStatus'                      => 'Thiết bị : Cập nhật trạng thái',
        '@site.Device.Update'                            => 'Thiết bị : Cập nhật',
        '@site.Device.Index'                             => 'Thiết bị : Danh sách',
        '@site.Device.Import'                            => 'Thiết bị : Import',
        '@site.Device.Delete'                            => 'Thiết bị : Xóa',
        '@site.Device.Create'                            => 'Thiết bị : Tạo',
        '@site.Device.ChangeDealer'                      => 'Thiết bị : Chuyển đại lý',

        '@site.Dealer.ViewUser'                          => 'Đại lý : Xem thông tin người quản trị',
        '@site.Dealer.View'                              => 'Đại lý : Xem',
        '@site.Dealer.UpdateUser'                        => 'Đại lý : Cập nhật thông tin người quản trị',
        '@site.Dealer.Update'                            => 'Đại lý : Cập nhật',
        '@site.Dealer.SelectAdmin'                       => 'Đại lý : Chọn người quản trị',
        '@site.Dealer.Pause'                             => 'Đại lý : Tạm dừng',
        '@site.Dealer.Index'                             => 'Đại lý : Danh sách',
        '@site.Dealer.DeleteUser'                        => 'Đại lý : Xóa người quản trị',
        '@site.Dealer.Delete'                            => 'Đại lý : Xóa',
        '@site.Dealer.CreateUser'                        => 'Đại lý : Tạo người quản trị',
        '@site.Dealer.Create'                            => 'Đại lý : Tạo',
        '@site.Dealer.ChangePassword'                    => 'Đại lý : Thay đổi mật khẩu người quản trị',

        // '@site.Credential.View'                          => 'Credential : View',
        // '@site.Credential.Update'                        => 'Credential : Update',
        // '@site.Credential.Index'                         => 'Credential : Index',
        // '@site.Credential.Delete'                        => 'Credential : Delete',
        // '@site.Credential.Create'                        => 'Credential : Create',

        '@site.ContentViewLog.View'                      => 'Log nội dung : Xem',
        '@site.ContentViewLog.Update'                    => 'Log nội dung : Sửa',
        '@site.ContentViewLog.Index'                     => 'Log nội dung : Xem danh sách',
        '@site.ContentViewLog.Delete'                    => 'Log nội dung : Xóa',
        '@site.ContentViewLog.Create'                    => 'Log nội dung : Tạo',

        '@site.ContentRelatedAsm.View'                   => 'Nội dung liên quan : Xem',
        '@site.ContentRelatedAsm.Update'                 => 'Nội dung liên quan : Sửa',
        '@site.ContentRelatedAsm.Index'                  => 'Nội dung liên quan : Xem danh sách',
        '@site.ContentRelatedAsm.Delete'                 => 'Nội dung liên quan : Xóa',
        '@site.ContentRelatedAsm.Create'                 => 'Nội dung liên quan : Tạo',

        '@site.ContentProfile.ViewModalData'             => 'File nội dung : Hiển thị popup',
        '@site.ContentProfile.View'                      => 'File nội dung : Xem chi tiết',
        '@site.ContentProfile.UpdateModalData'           => 'File nội dung : Hiển thị popup cập nhật',
        '@site.ContentProfile.Index'                     => 'File nội dung : Xem danh sách',
        '@site.ContentProfile.Editable'                  => 'File nội dung : Sửa thông tin',

        '@site.ContentLog.View'                          => 'Log của nội dung : Xem',
        '@site.ContentLog.Update'                        => 'Log của nội dung : Sửa',
        '@site.ContentLog.Index'                         => 'Log của nội dung : Xem danh sách',
        '@site.ContentLog.Delete'                        => 'Log của nội dung : Xóa',
        '@site.ContentLog.Create'                        => 'Log của nội dung : Tạo',

        '@site.ContentFeedback.View'                     => 'Nhận xét về nội dung : Xem',
        '@site.ContentFeedback.Update'                   => 'Nhận xét về nội dung : Sửa',
        '@site.ContentFeedback.Reject'                   => 'Nhận xét về nội dung : Từ chối',
        '@site.ContentFeedback.Index'                    => 'Nhận xét về nội dung : Xem danh sách',
        '@site.ContentFeedback.Delete'                   => 'Nhận xét về nội dung : Xóa',
        '@site.ContentFeedback.Create'                   => 'Nhận xét về nội dung : Tạo',
        '@site.ContentFeedback.Approve'                  => 'Nhận xét về nội dung : Duyệt',

        '@site.Content.View'                             => 'Nội dung : Xem chi tiết',
        '@site.Content.UpdateContent'                    => 'Nội dung : Sửa trạng thái & giá',
        '@site.Content.Index'                            => 'Nội dung : Xem danh sách',

        '@site.AppAds.View'                              => 'Các ứng dụng quảng cáo : Xem',
        '@site.AppAds.Update'                            => 'Các ứng dụng quảng cáo : Sửa',
        '@site.AppAds.Index'                             => 'Các ứng dụng quảng cáo : Xem danh sách',
        '@site.AppAds.Delete'                            => 'Các ứng dụng quảng cáo : Xóa',
        '@site.AppAds.Create'                            => 'Các ứng dụng quảng cáo : Tạo',

        '@site.Ads.View'                                 => 'Quảng cáo : Xem',
        '@site.Ads.Update'                               => 'Quảng cáo : Sửa',
        '@site.Ads.Index'                                => 'Quảng cáo : Xem danh sách',
        '@site.Ads.Delete'                               => 'Quảng cáo : Xóa',
        '@site.Ads.Create'                               => 'Quảng cáo : Tạo',

        /**
         * cp permission ********************************************************************************
         */

//        '@dealer.Device.AssignSubscriber'                => 'Thiết bị > Gán thuê bao',
        '@dealer.Device.Index'                           => 'Thiết bị > Danh sách',
        '@dealer.Device.Update'                          => 'Thiết bị > Cập nhật',
        '@dealer.Device.View'                            => 'Thiết bị > Xem',

        '@dealer.Report.FindCategoryBySiteContent'       => 'Báo cáo: Tìm danh mục theo NCC và nội dung',
        '@dealer.Report.FindServiceBySite'               => 'Báo cáo: Tìm gói cước theo NCC',
        '@dealer.Report.SubscriberDaily'                 => 'Báo cáo: Báo cáo số lượng thuê bao',

        // '@dealer.Site.Index'                             => 'Site > Index',
        // '@dealer.Site.Login'                             => 'Site > Login',
        // '@dealer.Site.Logout'                            => 'Site > Logout',
        // '@dealer.Site.TestCancel'                        => 'Site > TestCancel',
        // '@dealer.Site.TestPurchaseContent'               => 'Site > TestPurchaseContent',
        // '@dealer.Site.TestPurchaseDownload'              => 'Site > TestPurchaseDownload',
        // '@dealer.Site.TestRegister'                      => 'Site > TestRegister',

        '@dealer.Subscriber.AssignDevicesForSubscriber'  => 'Thuê bao: Gán thiết bị cho thuê bao',
        '@dealer.Subscriber.CancelServicePackage'        => 'Thuê bao: Hủy gói',
        '@dealer.Subscriber.Create'                      => 'Thuê bao: Tạo',
        '@dealer.Subscriber.Delete'                      => 'Thuê bao: Xóa',
        '@dealer.Subscriber.ExtendServicePackage'        => 'Thuê bao: Gia hạn gói cước',
        '@dealer.Subscriber.Index'                       => 'Thuê bao: Danh sách',
        '@dealer.Subscriber.PurchaseServicePackages'     => 'Thuê bao: Mua gói cước',
//        '@dealer.Subscriber.ResendMt'                    => 'Thuê bao: ResendMt',
        '@dealer.Subscriber.UnassignDeviceForSubscriber' => 'Thuê bao: Bỏ gán thiết bị',
        '@dealer.Subscriber.Update'                      => 'Thuê bao: Cập nhật',
        '@dealer.Subscriber.View'                        => 'Thuê bao: Xem',

//        '@dealer.SubscriberDeviceAsm.Create'             => 'SubscriberDeviceAsm > Create',
//        '@dealer.SubscriberDeviceAsm.Delete'             => 'SubscriberDeviceAsm > Delete',
//        '@dealer.SubscriberDeviceAsm.Index'              => 'SubscriberDeviceAsm > Index',
//        '@dealer.SubscriberDeviceAsm.Update'             => 'SubscriberDeviceAsm > Update',
//        '@dealer.SubscriberDeviceAsm.View'               => 'SubscriberDeviceAsm > View',

        // '@dealer.SumContent.Create'                      => 'SumContent > Create',
        // '@dealer.SumContent.Delete'                      => 'SumContent > Delete',
        // '@dealer.SumContent.Index'                       => 'SumContent > Index',
        // '@dealer.SumContent.Update'                      => 'SumContent > Update',
        // '@dealer.SumContent.View'                        => 'SumContent > View',

        // '@dealer.SumContentView.Create'                  => 'SumContentView > Create',
        // '@dealer.SumContentView.Delete'                  => 'SumContentView > Delete',
        // '@dealer.SumContentView.Index'                   => 'SumContentView > Index',
        // '@dealer.SumContentView.Update'                  => 'SumContentView > Update',
        // '@dealer.SumContentView.View'                    => 'SumContentView > View',

        '@dealer.User.AddAuthItem'                       => 'Người dùng: Phân quyền',
        '@dealer.User.ChangePassword'                    => 'Người dùng: Đổi mật khẩu',
        '@dealer.User.Create'                            => 'Người dùng: Thêm mới',
        '@dealer.User.Delete'                            => 'Người dùng: Xóa',
        '@dealer.User.Index'                             => 'Người dùng: Xem danh sách',
        '@dealer.User.Info'                              => 'Người dùng: Xem thông tin người quản trị',
        '@dealer.User.OwnerChangePassword'               => 'Người dùng: Đổi mật khẩu người dùng hiện tại',
        '@dealer.User.ResetPassword'                     => 'Người dùng: Khôi phục mật khẩu',
        '@dealer.User.RevokeAuthItem'                    => 'Người dùng: Xóa quyền',
        '@dealer.User.Update'                            => 'Người dùng: Cập nhật',
        '@dealer.User.UpdateOwner'                       => 'Người dùng: Cập nhật người dùng hiện tại',
        '@dealer.User.View'                              => 'Người dùng: Xem chi tiết',
    ];

    public function actionRedescription()
    {
        $changed = [];
        foreach ($this->mapping as $key => $value) {
            $permission = AuthItem::findOne(['name' => $key]);

            if ($permission) {
                $permission->description = $value;

                if ($permission->save(false)) {
                    $changed[] = $permission->name;
                    echo $value . "\r\n";
                }
            }
        }

        AuthItem::deleteAll(['AND', ['NOT IN', 'name', $changed], ['type' => AuthItem::TYPE_PERMISSION]]);
    }
}
